# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: gh:jdelfino/devcontainer-template
_commit: 730756d7a85c4948cb2f3017daa24107320685a9
project_name: coding-tool
project_description: "Real-time coding classroom tool"
base_container: node
add_python: true
add_node: false
add_go: false
add_java: false
add_rust: false
use_1password: true
op_vault: coding-tool-dev
