/**
 * Analysis types for AI-powered code walkthrough
 *
 * Defines the structure for LLM-generated walkthrough scripts that help
 * instructors discuss student submissions during lectures.
 */

/**
 * Category of a walkthrough entry
 */
export type WalkthroughCategory =
  | 'common-error'
  | 'edge-case'
  | 'interesting-approach'
  | 'exemplary';

/**
 * A single entry in the walkthrough script
 */
export interface WalkthroughEntry {
  /** Position in the ordered sequence (1-indexed for display) */
  position: number;

  /** Anonymous student reference (e.g., "Student A", "Student B") */
  studentLabel: string;

  /** Internal student ID (used for featuring on public view) */
  studentId: string;

  /** Short discussion points (2-4 bullets, 5-15 words each) */
  discussionPoints: string[];

  /** Brief explanation of why this submission is worth discussing */
  pedagogicalNote: string;

  /** Category for filtering/visual distinction */
  category: WalkthroughCategory;
}

/**
 * Summary statistics for the walkthrough
 */
export interface WalkthroughSummary {
  /** Total number of students in the session */
  totalSubmissions: number;

  /** Number of submissions filtered out (empty/unchanged) */
  filteredOut: number;

  /** Number of submissions sent to LLM for analysis */
  analyzedSubmissions: number;

  /** Common patterns observed across submissions (2-3 items) */
  commonPatterns: string[];

  /** Warning message if many submissions were filtered */
  warning?: string;
}

/**
 * The complete walkthrough script generated by LLM analysis
 */
export interface WalkthroughScript {
  /** Session ID this script was generated for */
  sessionId: string;

  /** Ordered list of submissions to discuss */
  entries: WalkthroughEntry[];

  /** Summary statistics and patterns */
  summary: WalkthroughSummary;

  /** Timestamp when this script was generated */
  generatedAt: Date;
}

/**
 * Request payload for the analyze endpoint
 */
export interface AnalyzeCodeRequest {
  /** No additional parameters needed - session ID is in URL */
}

/**
 * Response from the analyze endpoint
 */
export interface AnalyzeCodeResponse {
  success: boolean;
  script?: WalkthroughScript;
  error?: string;
}

/**
 * Input for the Gemini analysis service
 */
export interface AnalysisInput {
  /** Session ID for reference */
  sessionId: string;

  /** Problem title and description */
  problemTitle: string;
  problemDescription: string;

  /** Starter code (for filtering unchanged submissions) */
  starterCode: string;

  /** Student submissions to analyze */
  submissions: Array<{
    studentId: string;
    code: string;
  }>;
}

/**
 * Raw response structure expected from Gemini API
 */
export interface GeminiAnalysisResponse {
  entries: Array<{
    studentLabel: string;
    discussionPoints: string[];
    pedagogicalNote: string;
    category: string;
  }>;
  commonPatterns: string[];
}
