#!/bin/bash
# setup-secrets.sh - Start local Supabase and write .env.local for local-only dev.
# Runs via postStartCommand (every container start).
#
# No external accounts or shared secrets: keys come entirely from the local
# Supabase stack. The AI walkthrough (Gemini) and rate limiting (Upstash) stay
# disabled in the classroom — their vars are written empty on purpose.
set -euo pipefail

cd "$(dirname "$0")/.."

# Start local Supabase (idempotent: no-op if already running).
echo "Starting local Supabase..."
supabase start

# Extract the locally-generated keys. `supabase status -o env` emits ANON_KEY /
# SERVICE_ROLE_KEY; the app reads them under its own var names (see below).
eval "$(supabase status -o env | grep -E '^(ANON_KEY|SERVICE_ROLE_KEY)=')"

if [ -z "${ANON_KEY:-}" ] || [ -z "${SERVICE_ROLE_KEY:-}" ]; then
    echo "ERROR: Could not extract Supabase keys from 'supabase status -o env'"
    exit 1
fi

# Write .env.local directly. The app reads NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
# and SUPABASE_SECRET_KEY, so map the anon/service_role keys onto those names.
cat > .env.local <<EOF
# Generated by .devcontainer/setup-secrets.sh on container start. Do not edit by
# hand — it is overwritten every start and is gitignored. Local-only dev: no
# external accounts or shared secrets.

# System admin bootstrap (first user with this email is elevated to system-admin)
SYSTEM_ADMIN_EMAIL=admin@test.local

# Local Supabase (keys generated by the local stack)
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
SUPABASE_SECRET_KEY=${SERVICE_ROLE_KEY}

# AI walkthrough (Gemini) — disabled in the classroom (leave empty)
GEMINI_API_KEY=

# Rate limiting (Upstash) — disabled in local dev (leave empty)
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=
EOF

echo "Wrote .env.local (local Supabase URL + keys; Gemini/Upstash left empty)."
